### PR TITLE
Remove unused channel from shell struct

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Review by gbraad — APPROVED** [review]

**Comment by gbraad** [comment]
@jsliacan you decide if to merge or not. You still intended to use this?

**Comment by gbraad** [comment]
@praveenkumar commit description: "belog"

**Comment by jsliacan** [comment]
@praveenkumar , is this related to the problem that @adrianriobo described recently? E.g. exitcode "getting lost" in the depths of the space between the shell and cucumber? :)

**Comment by adrianriobo** [comment]
Yes, the problem is related with the pipes in the shell structure. Already talk to @praveenkumar about what I found so far.

**Pull request merged**
